{'Package': 'python-weberror', 'Version': '0.13.1+dfsg-1', 'Installed-Size': '208', 'Maintainer': 'Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>', 'Architecture': 'all', 'Depends': [['python-paste', '>=', '1.7.1'], 'python-pygments', 'python-tempita', 'python-webob', ['python:any', '<<', '2.8'], ['python:any', '>=', '2.7.5-5~'], 'python-pastedeploy', 'python-pkg-resources', ['python', '>=', '2.6)'], 'libjs-jquery'], 'Description': 'Python web error handling and exception catching module', 'Homepage': 'https://pypi.python.org/pypi/WebError', 'Description-md5': '473b922127ee671c1a854ba702046bd8', 'Section': 'python', 'Priority': 'extra', 'Filename': 'pool/main/p/python-weberror/python-weberror_0.13.1+dfsg-1_all.deb', 'Size': '47746', 'SHA256': 'e87521e6fe9e0cfc4f7c53a11a3af38ee441c52baeb49d558a4a784f868a9574'}