{'Package': 'python-zope.dottedname', 'Source': 'zope.dottedname', 'Version': '3.4.6-5', 'Installed-Size': '110', 'Maintainer': 'Debian/Ubuntu Zope Team <pkg-zope-developers@lists.alioth.debian.org>', 'Architecture': 'all', 'Depends': ['python2.7 | python2.6', ['python', '>=', '2.6.6-7~'], ['python', '<<', '2.8'], 'python-pkg-resources'], 'Conflicts': 'zope3', 'Description': 'Resolver for Python dotted names', 'Homepage': 'http://pypi.python.org/pypi/zope.dottedname', 'Description-md5': '16992f0c38c81b8943ab3cdf80e347e7', 'Section': 'python', 'Priority': 'extra', 'Filename': 'pool/main/z/zope.dottedname/python-zope.dottedname_3.4.6-5_all.deb', 'Size': '7536', 'SHA256': 'd9ab871009a3fb7231216dfe9b9276f268f2511867d0d7b9e1417d682883bb87'}