{'Package': 'python3-zope.security', 'Source': 'zope.security (4.0.3-2)', 'Version': '4.0.3-2+b3', 'Installed-Size': '614', 'Maintainer': 'Debian/Ubuntu Zope Team <pkg-zope-developers@lists.alioth.debian.org>', 'Architecture': 'amd64', 'Depends': [['python3', '<<', '3.8'], ['python3', '>=', '3.6~'], 'python3-pkg-resources', 'python3-zope.component', 'python3-zope.i18nmessageid', 'python3-zope.interface', 'python3-zope.location', 'python3-zope.proxy', 'python3-zope.schema', ['python3:any', '>=', '3.3.2-2~'], ['libc6', '>=', '2.4']], 'Conflicts': 'zope3', 'Description': 'Zope Security Framework', 'Homepage': 'http://pypi.python.org/pypi/zope.security', 'Description-md5': 'e9f54e364b11459c8fb9ffe7642eb3bf', 'Section': 'zope', 'Priority': 'extra', 'Filename': 'pool/main/z/zope.security/python3-zope.security_4.0.3-2+b3_amd64.deb', 'Size': '79392', 'SHA256': '404e2cfe1168912ee5e02fc376e1452bd241bed59ee11e90fbe4a0fa89969281'}