{'Package': 'python-zdaemon', 'Source': 'zdaemon', 'Version': '2.0.7-1', 'Installed-Size': '285', 'Maintainer': 'Debian/Ubuntu Zope Team <pkg-zope-developers@lists.alioth.debian.org>', 'Architecture': 'all', 'Provides': 'python2.6-zdaemon, python2.7-zdaemon', 'Depends': ['python2.7 | python2.6', ['python', '>=', '2.6.6-7~'], ['python', '<<', '2.8'], 'python-zconfig', 'python-pkg-resources'], 'Conflicts': 'zope3', 'Description': 'daemon process control library and tools for Unix-based systems', 'Homepage': 'http://pypi.python.org/pypi/zdaemon', 'Description-md5': '761f8913e1ddea787af8398012cd07d6', 'Section': 'zope', 'Priority': 'extra', 'Filename': 'pool/main/z/zdaemon/python-zdaemon_2.0.7-1_all.deb', 'Size': '54966', 'SHA256': 'e032bc0283996e3c6e55d7d42aadb4f4cf0b630aa7033a2e645ef619327138a7'}