{'Package': 'python-zope.i18nmessageid', 'Source': 'zope.i18nmessageid (4.0.3-2)', 'Version': '4.0.3-2+b4', 'Installed-Size': '61', 'Maintainer': 'Debian/Ubuntu Zope Team <pkg-zope-developers@lists.alioth.debian.org>', 'Architecture': 'amd64', 'Depends': [['python', '<<', '2.8'], ['python', '>=', '2.7~'], 'python-pkg-resources', ['python:any', '<<', '2.8'], ['python:any', '>=', '2.7.5-5~'], ['libc6', '>=', '2.4']], 'Conflicts': 'zope3', 'Description': 'Message Identifiers for internationalization', 'Homepage': 'http://pypi.python.org/pypi/zope.i18nmessageid', 'Description-md5': '4484ca5e9a74d928f306c3f4c34308f5', 'Section': 'python', 'Priority': 'extra', 'Filename': 'pool/main/z/zope.i18nmessageid/python-zope.i18nmessageid_4.0.3-2+b4_amd64.deb', 'Size': '13628', 'SHA256': '043b9e1389f8b7c00e8fa86eacc7bd6c7f0eda480dee14c03797c12a8d596359'}